# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 526db5ac2437e86668ccb533e97ad8d4d1f57655b25d49b0193f94f145c416d2a6ff826d3e82fac7344c8c0e3fe7348d06a4e7a09c3768fbd4a711789e724440

test:
  secret_key_base: 04063f0c3842a9adf09af09d55bb155ef774cb0fcf6eae3beec811727b8cd0f52f93bc1629e263d861d91543c205f9a6264062eeed0485d6cd10d73b32a9d7a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
